# Exercise 1
Convert a 1D array to a 2D array with 2 rows
<pre>arr=np.arange(10)</pre>
<br>
We want:  
<pre>
array([[0, 1, 2, 3, 4],
	   [5, 6, 7, 8, 9]])
</pre>

In [4]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all" 

import numpy as np
arr = np.arange(10)
#arr.shape=(2,-1)
arr=arr.reshape(2, -1)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Exercise 2

Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [5]:
arr = np.arange(100, 200, 10)
arr
arr = arr.reshape(5,2)
arr

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

# Exercise 3

Given the following array:
    
<pre>arr = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])</pre>

Create an array composed of the 3rd column of each row of `arr`

In [6]:
arr = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
narr = arr[...,2]
narr
# or
narr = arr[:,2]
narr

array([33, 66, 99])

array([33, 66, 99])

# Exercise 4

Create an 8X3 integer array from a range between 10 to 34.

Then Split the array into four equal-sized 2x3 sub-arrays.


In [14]:
arr = np.arange(10, 34, 1).reshape(8,3)
subArrs = np.split(arr, 4) 
subArrs

[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

# Exercise 5

Given the array:

    arr = np.array([[34,43,73],[82,22,12],[53,94,66]]) 

delete it's second column.

Then, using the method `insert()` insert the following new column as the second column:

    col = np.array([[10,10,10]])
    

In [16]:
arr = np.array([[34,43,73],[82,22,12],[53,94,66]])
col = np.array([[10,10,10]])
arr
arr = np.delete(arr , 1, axis = 1) 
arr
arr = np.insert(arr , 1, col, axis = 1) 
arr
# Second option:
arr = np.array([[34,43,73],[82,22,12],[53,94,66]])
arr[:,1]=col
arr

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

array([[34, 73],
       [82, 12],
       [53, 66]])

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

# Exercise 6

Replace all odd numbers in arr with -1 without changing arr and then by changing arr

<pre>arr=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])</pre>


In [27]:
arr=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) # or arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
arr
out

arr = np.arange(10)
arr[arr % 2 == 1] = -1
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# Exercise 7

How to get the positions where elements of two arrays match?

<pre>
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
</pre>

In [17]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)
a[a == b]

(array([1, 3, 5, 7], dtype=int64),)

array([2, 2, 4, 4])

# Exercise 8

How to remove from one array those items that exist in another?

<pre>
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
</pre>

In [7]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = np.array([5,6,7,8,9])

# From 'a' remove all of 'b'
# %timeit  np.setdiff1d(a,b)
np.setdiff1d(a,b)

# Without Numpy :
diff_array = [i for i in a if i not in b]
diff_array

array([1, 2, 3, 4])

[1, 2, 3, 4]

# Exercise 9

How to stack two arrays horizontally
<pre>
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
</pre>
We want:  
<pre>
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
 		[5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
</pre>

In [21]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
a
b
# Method 1:
np.concatenate([a, b], axis=1)

# Method 2:
np.hstack([a, b])

# Method 3:
np.c_[a, b]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# Exercise 10

Get all items between 5 and 10 from a

<pre>
a = np.array([2, 6, 1, 9, 10, 3, 27])
</pre>

In [24]:
import numpy as np
a = np.array([2, 6, 1, 9, 10, 3, 27])

# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]

# Method 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

# Method 3: %timeit
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

array([ 6,  9, 10])

array([ 6,  9, 10])

# Exercise 11

Swap columns 1 and 2 in the array arr

<pre>
arr = np.arange(9).reshape(3,3)
</pre>

In [26]:
arr = np.arange(9).reshape(3,3)
arr

arr[:, [0,2,1]]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

# Exercise 12

How to find the count of unique values in the numpy array a?

<pre>
a = np.array([1,2,2,1,2,5])
</pre>

In [29]:
a = np.array([1,2,2,1,2,5,5,6,1,2,0])
a
np.unique(a, return_counts=True)

for val,count in zip(*np.unique(a, return_counts=True)):
    print(f"value: {val} occurences: {count}")
    


array([1, 2, 2, 1, 2, 5, 5, 6, 1, 2, 0])

(array([0, 1, 2, 5, 6]), array([1, 3, 4, 2, 1], dtype=int64))

value: 0 occurences: 1
value: 1 occurences: 3
value: 2 occurences: 4
value: 5 occurences: 2
value: 6 occurences: 1


18

# Exercise 13

Create a UFunc that will be able to **normalize** the array it receives as argument.

To normalize a value, subtract it from the minimum value of the dataset and divide it by using the difference between the maximum and minimum value of the dataset.
The lowest value in the data will have the value 0 and the highest value in the data will have the value 1 and the other values will be within the range 0 and 1.

In [4]:
import numpy as np

def NormalizeData(data):
    return (data - np.min(data)) / (np.max(data) - np.min(data))

X = np.array([
    [ 0,  1],
    [ 2,  3],
    [ 4,  5],
    [ 6,  7],
    [ 8,  9],
    [10, 11],
    [12, 13],
    [14, 15]
])
# <=> X=np.arange(16, dtype=int).reshape(8,2)

scaled_x = NormalizeData(X)
scaled_x

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


array([[0.        , 0.06666667],
       [0.13333333, 0.2       ],
       [0.26666667, 0.33333333],
       [0.4       , 0.46666667],
       [0.53333333, 0.6       ],
       [0.66666667, 0.73333333],
       [0.8       , 0.86666667],
       [0.93333333, 1.        ]])